### ISSUE TITLE
\Humbug\Mutator\ReturnValue\FunctionCall doesn't work when there is one more return statement within the function return statement

### ISSUE THREAD

**Issue by MazeChaZer** [humbug/humbug#167] opened 2016-02-17 13:04 UTC
``` php
public function surroundWithBrackets($array)
{
    return array_map(function ($string) {
        return "($string)";
    }, $array);
}
```

If I run humbug on this function, it is reported as "not covered" (although there is a line coverage of 100%).

I'm attaching a complete sample project where this is happening.

[humbug-bug-example.zip](https://github.com/padraic/humbug/files/134298/humbug-bug-example.zip)

**Comment by theofidry** [comment] 2017-04-19 23:16
Closing as a duplicate of #213. Functions should not be mutated.

**Closed by theofidry** 2017-04-19 23:16 UTC
