### ISSUE TITLE
PHPUnit Mock and Prophecy objects shoudn't be mutated

### ISSUE THREAD

**Issue by piotr-zuralski** [humbug/humbug#227] opened 2017-04-18 12:14 UTC
I think that created Mock and Prophecy objects shouldn’t be mutated, right now they are.

e.g.:
```php
$response = $this->createMock(ResponseInterface::class);
$response->method('getStatusCode')->willReturn(200);
$response->method('getBody')->willReturn('Hello');
$this->httpClient->method('request')->with('POST', $this->searchUrl)->willReturn($response);
```
right now Humbug will report that mutating 200 on 201 also will result in mutant that escaped, but that's not the real code that we test and that we intent to be mutated. 
Or do you have different point of view on that?

**Comment by theofidry** [comment] 2017-04-19 22:50
Actually how Humbug is mutating them? Surely your mocks should not be in your source code.

**Comment by padraic** [comment] 2017-05-05 14:11
Closing. I'm guessing the problem is that Himbug was configured with a root directory containing both source and tests. The readme offers a few ways of configuration and supports excludes.

**Closed by padraic** 2017-05-05 14:11 UTC
Labels: question

**Comment by piotr-zuralski** [comment] 2017-09-28 21:33
humbug was mutating `200` in the code, same with `true` and `false`, when creating mocks and using prophecy

**Comment by theofidry** [comment] 2017-09-29 08:04
@piotr-zuralski but if you exclude the `tests` folder it won't try to mutate this code right?

**Comment by piotr-zuralski** [comment] 2017-09-29 11:49
Right, now it works like it should. Sorry for bothering for such a trivial thing :wink:
